package:
  name: conda-pypi
  {% if GIT_DESCRIBE_TAG is defined and GIT_BUILD_STR is defined %}
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}
  {% else %}
  version: 0.0.0dev0
  {% endif %}

source:
  # git_url only captures committed code
  git_url: ../

build:
  # can't be noarch because we can't place EXTERNALLY-MANAGED in stdlib (first level is site-packages)
  number: 0
  script:
    - set -x  # [unix]
    - "@ECHO ON"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    - {{ PYTHON }} -c "import sys; from conda_pypi.utils import ensure_externally_managed; ensure_externally_managed(sys.prefix)"

requirements:
  host:
    - python
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - conda >=24.11.0
    - conda-index
    - conda-package-streaming
    - conda-libmamba-solver
    - importlib_resources  # [py<39]
  run:
    - python
    - conda >=24.11.0
    - pip >=23.0.1
    - grayskull
    - conda-index
    - conda-package-streaming
    - conda-libmamba-solver
    - packaging

test:
  requires:
    - conda-pypi  # Ensure conda-pypi is installed to trigger post-command hook
  imports:
    - conda_pypi
    - conda_pypi.main
  commands:
    - conda pypi --help
    - python -c "import sys; from conda_pypi.utils import get_env_stdlib; assert (get_env_stdlib(sys.prefix) / 'EXTERNALLY-MANAGED').exists()"
    - pip install --no-deps colorama==0.4.4 && exit 1 || exit 0

about:
  home: https://github.com/conda-incubator/conda-pypi
  license: MIT
  license_file: LICENSE
  summary: Better PyPI interoperability for the conda ecosystem
  dev_url: https://github.com/conda-incubator/conda-pypi
