[project]
name = "conda-pip"
version = "0.1.0"
description = "`pip` wrappers to make it work with `conda` in a better way."
authors = ["jaimergp <jaimergp@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
dev = "python -mpip install -e. --no-deps"
test = "pytest -vvv"

[dependencies]
python = "3.10"
conda = ">=23.9"
pip = "*"
grayskull = "*"
pytest = "7.4.3.*"
