"""
Install a wheel.
"""

import subprocess
import sys
import sysconfig

from installer import install
from installer.destinations import SchemeDictionaryDestination
from installer.sources import WheelFile


def install_installer(python_executable, whl, build_path):
    # Handler for installation directories and writing into them.
    destination = SchemeDictionaryDestination(
        sysconfig.get_paths(),
        interpreter=sys.executable,
        script_kind="posix",
    )

    with WheelFile.open("sampleproject-1.3.1-py2.py3-none-any.whl") as source:
        install(
            source=source,
            destination=destination,
            # Additional metadata that is generated by the installation tool.
            additional_metadata={
                "INSTALLER": b"amazing-installer 0.1.0",
            },
        )


def install_pip(python_executable, whl, build_path):
    command = [
        python_executable,
        "-m",
        "pip",
        "install",
        "--no-deps",
        "--target",
        str(build_path / "site-packages"),
        whl,
    ]
    subprocess.run(command, check=True)
    print("Installed to", build_path)
