name: Sphinx
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sphinx:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pupa
          environment-file: environment.yml
          python-version: 3.12
      - name: Build Documentation
        shell: bash -el {0}
        run: |
          pip install hatchling hatch-vcs editables
          pip install sphinx sphinx-copybutton sphinx-design sphinx-sitemap sphinx-reredirects myst-parser conda-sphinx-theme linkify-it-py pypi-simple
          pip install -e . --no-build-isolation
          make html
